Persist username across launches using UserDefaults
marwanhawari/LeetBar pull request #1
Opened 2022-09-10 16:49 UTC by juanj

Hi!
First of all, I wanted to thank you for this project! It is nice to have a quick way of checking your LeetCode progress, and access the daily problem.
I have been using it for a while, and one thing that is a bit tedious, is that you need to enter the username each time you launch the app.

This PR aims to solve that by persisting the username using `UserDefaults`.

Let me know if these changes are OK, or if you have any comments.

2022-09-10 20:21 UTC, marwanhawari commented
Awesome, this is a great idea! I think there is a much simpler implementation though. We could just add a `didSet` property observer on the `@Published username` property so that every time it changes it will be saved to `UserDefaults`. Then in the `init()` for the viewmodel we can set `self.username` to the value from `UserDefaults` and default to empty string if not found.

Something like this:
```swift
    @Published var username: String {
        didSet {
            UserDefaults.standard.set(username, forKey: "username")
        }
    }
```

```swift
    init(service: HTTPLeetService = LeetService()) {
        self.service = service
        self.username = UserDefaults.standard.string(forKey: "username") ?? ""
    }
```

What do you think?

2022-09-10 22:25 UTC, juanj commented
I may have overengineered it a little 😅. My idea was to avoid creating a direct dependency from `ViewModel` to `UserDefaults`.

Of course, using `UserDefaults` directly is a lot simpler, but that doesn't smell right...

I have no issue with updating the code following your suggestions, but will like to ask you to consider if that's the route we want to go. Just give me a heads-up and I will update the code.

2022-09-11 05:48 UTC, marwanhawari commented
Ah, I see what you're saying but it seems like a lot of additional complexity for a relatively simple feature haha. I think it's okay for now to just access `UserDefaults` directly.

2022-09-11 14:45 UTC, juanj commented
Updated!

2022-09-11 17:37 UTC, marwanhawari requested changes

2022-09-11 17:37 UTC, marwanhawari commented on LeetBar/ViewModels/ViewModel.swift
> +    @Published var username: String = "" {
minor thing, but I don't think there needs to be a default value here.

2022-09-11 17:37 UTC, marwanhawari commented on LeetBar/ViewModels/ViewModel.swift
> +        username = UserDefaults.standard.string(forKey: "username") ?? ""
this is stylistic, but I tend to use `self.` in front of properties in the `init()`

2022-09-11 22:17 UTC, marwanhawari approved these changes

2022-09-11 22:20 UTC, marwanhawari commented
Looks good, thanks for contributing! I'll upload the new build later today.

2022-09-11 22:21 UTC, merged